2024-01-17 15:08:12,565 - root - ERROR - This is an error message.
2024-01-17 15:44:23,999 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "/home/riken/.local/lib/python3.10/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

2024-01-17 15:53:31,066 - root - ERROR - This is an error message.
2024-01-17 15:53:42,119 - root - ERROR - This is an error message.
2024-01-17 15:53:49,119 - root - ERROR - This is an error message.
2024-01-17 15:54:21,574 - root - ERROR - This is an error message.
2024-01-17 15:54:27,557 - root - ERROR - This is an error message.
2024-01-17 15:54:32,091 - root - ERROR - This is an error message.
2024-01-17 15:54:35,944 - root - ERROR - This is an error message.
2024-01-17 15:54:41,921 - root - ERROR - This is an error message.
2024-01-17 15:54:48,365 - root - ERROR - This is an error message.
2024-01-17 15:54:50,655 - root - ERROR - This is an error message.
2024-01-17 15:54:56,890 - root - ERROR - This is an error message.
2024-01-17 16:07:14,650 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "/home/riken/.local/lib/python3.10/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

2024-01-17 16:10:13,254 - root - ERROR - This is an error message.
2024-01-17 16:10:28,947 - root - ERROR - This is an error message.
2024-01-17 16:10:37,421 - root - ERROR - This is an error message.
2024-01-17 16:10:41,759 - root - ERROR - This is an error message.
2024-01-17 16:11:14,891 - root - ERROR - This is an error message.
2024-01-17 16:11:17,544 - root - ERROR - This is an error message.
2024-01-17 16:11:30,443 - root - ERROR - This is an error message.
2024-01-17 16:11:41,337 - root - ERROR - This is an error message.
2024-01-17 16:11:52,050 - root - ERROR - This is an error message.
2024-01-17 16:12:00,408 - root - ERROR - This is an error message.
2024-01-17 16:12:03,235 - root - ERROR - This is an error message.
2024-01-17 16:12:10,213 - root - ERROR - This is an error message.
2024-01-17 16:12:11,968 - root - ERROR - This is an error message.
2024-01-17 16:12:15,564 - root - ERROR - This is an error message.
2024-01-17 16:12:21,932 - root - ERROR - This is an error message.
2024-01-17 16:12:27,967 - root - ERROR - This is an error message.
2024-01-17 16:12:31,062 - root - ERROR - This is an error message.
2024-01-17 16:16:39,349 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "/home/riken/.local/lib/python3.10/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

